### ISSUE TITLE
Add Convert Spaces to &nbsp;

### ISSUE THREAD

**Issue by oceansblue** [akalongman/sublimetext-stringutilities#21]
Convert Chars to Html Entities  Convert Spaces to &nbsp; 
Spaces is so important .

**Comment by opg7371** [comment]
Should i make this change to every file?
@oceansblue @akalongman

**Comment by akalongman** [comment]
You must add new function for that and show in context menu

**Comment by anshuman73** [comment]
Hi, if this issue is resolved, can it be closed ?
