### ISSUE TITLE
Convert HTML Entities to Chars

### ISSUE THREAD

**Issue by derikmacedo** [akalongman/sublimetext-stringutilities#8]
"Convert HTML Entities to Chars" not working
![2015-08-27_16-36-48](https://cloud.githubusercontent.com/assets/4296793/9531147/ad79eaf8-4cda-11e5-823c-057d75912bd5.png)

**Comment by akalongman** [comment]
Any error in console?

**Comment by derikmacedo** [comment]
Nothing. S.O Win7 x64. ST3 last build.

**Comment by weisk** [comment]
```
File "/Users/fran/Library/Application Support/Sublime Text 3/Packages/StringUtilities/stringutilities.py", line 66, in run
    text = re.sub('&(%s);' % '|'.join(htmlentitydefs.name2codepoint)
```
`NameError: global name 'htmlentitydefs' is not defined`

I think you upgraded the old `import htmlentityfdefs` to `import html.entities` (migration from python 2 to 3), but forgot to replace the occurrences on the code. Just doing `import html.entities as htmlentitydefs` fixes it.

**Comment by akalongman** [comment]
Thanks for support. You can send to me pull request

**Comment by derikmacedo** [comment]
Perfect! Now it's working..
